### ISSUE TITLE
Broken handling of UUIDs as Strings with Oracle Database in vertx 4.3.5+

### ISSUE THREAD

**Issue by smithp1010** [vert-x3/vertx-jdbc-client#295] opened 2022-12-12 17:35 UTC
When using vertx 4.3.5 with an Oracle Database, the behaviour of a tuple sourced from a string representing a UUID has changed. 

Using the below oracle table and test case with vertx 4.3.4, two records are successfully inserted into the table with the  appropriate values in the varchar field. Once the code is upgraded to use vertx 4.3.5 however, the second insert always throws an exception.

Oracle Table

CREATE TABLE TEST_TAB (
    TXT_REF VARCHAR(255)
 )
 
Test case

```
import io.vertx.core.Future;
import io.vertx.core.Promise;
import io.vertx.core.Vertx;
import io.vertx.jdbcclient.JDBCConnectOptions;
import io.vertx.jdbcclient.JDBCPool;
import io.vertx.sqlclient.PoolOptions;
import io.vertx.sqlclient.Row;
import io.vertx.sqlclient.RowSet;
import io.vertx.sqlclient.Tuple;

import java.nio.charset.StandardCharsets;
import java.util.UUID;

public class JdbcTest {

  public static void main(String[] args) {
    JDBCConnectOptions options = new JDBCConnectOptions();
    options.setJdbcUrl("jdbc:oracle:thin:@localhost:1521:XE");
    options.setUser("username");
    options.setPassword("password");
    options.setIdleTimeout(1200000);
    PoolOptions poolOptions = new PoolOptions().setMaxSize(30);
    Vertx vertx = Vertx.vertx();

    JDBCPool pool = JDBCPool.pool(vertx, options, poolOptions);

    String sql = "insert into TEST_TAB VALUES (?)";

    // This works
    executeSQL(pool, sql, "123456")

      // This fails in 4.3.5...
      .compose( v2 -> executeSQL(pool, sql, UUID.randomUUID().toString()) );
  }

  private static Future<Void> executeSQL(JDBCPool pool, String sql, Object tup) {
    Promise<Void> promise = Promise.promise();

    Tuple tuple = Tuple.of(tup);

    var fut = pool.preparedQuery(sql).execute(tuple);

    fut.onSuccess(rows -> {
      System.out.println("SQL Good with ["+tup+"]");
    }).onFailure(t -> {
        System.out.println("SQL Bad with ["+tup+"]");
        t.printStackTrace();
    }).onComplete(v -> promise.complete());

    return promise.future();
  }
}
```

Output with 4.3.4:

SQL Good with [123456]
SQL Good with [84fe9ae0-34a7-4f10-9f42-e04714602c47]

Output with 4.3.5:

SQL Good with [123456]
SQL Bad with [b923e354-0e75-47d6-9699-dc63c7890516]
java.sql.SQLException: Invalid column type
	at oracle.jdbc.driver.OraclePreparedStatement.setObjectCritical(OraclePreparedStatement.java:8782)
	at oracle.jdbc.driver.OraclePreparedStatement.setObjectInternal(OraclePreparedStatement.java:8264)
	at oracle.jdbc.driver.OraclePreparedStatement.setObjectInternal(OraclePreparedStatement.java:9039)
	at oracle.jdbc.driver.OraclePreparedStatement.setObject(OraclePreparedStatement.java:9014)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.setObject(OraclePreparedStatementWrapper.java:221)
	at io.agroal.pool.wrapper.PreparedStatementWrapper.setObject(PreparedStatementWrapper.java:289)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.fillStatement(JDBCPreparedQuery.java:142)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:63)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:44)
	at io.vertx.ext.jdbc.impl.JDBCConnectionImpl.lambda$schedule$3(JDBCConnectionImpl.java:219)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by yogeshkul** [comment] 2022-12-14 10:35
Try wrapping the param with Buffer.
Buffer.buffer(string)
Or
Buffer.buffer(uuid.string)

Worked for me

**Comment by smithp1010** [comment] 2022-12-14 15:33
Thanks for the work around: It does result in a successful save of a UUID into a varchar in Oracle. However I think the underlying bug needs fixing so code works as per when using previous versions of vertx. Without a fix, any code that isn't modified is at risk of exceptions if a UUID were to be entered into a string (possibly by bad actors who could enter UUIDs maliciously). 

I have been analysing further and have found the root cause of the issue: 
In 4.3.5 the JDBCPreparedQuery.fillStatement method has been changed to use the preparedStatement.getParameterMetaData() to work out parameter types:


![JDBCTypeOtherASUUID_0](https://user-images.githubusercontent.com/120391554/207634662-314a6ac6-c84b-4230-9aee-3faf9f9f66f9.PNG)

The metadata is used to obtain the JDBCPropertyAccessor.jdbcType and for a String parameter with Oracle, the jdbcType is equated to JdbcType.OTHER

![JDBCTypeOtherASUUID_01](https://user-images.githubusercontent.com/120391554/207634845-7fd16c49-8fda-4e64-a785-6ed1e618c857.PNG)

When the encode method is called on the vertx JDBCEncoderImpl class, there is special check for whether Strings that match a UUID format should be treated as UUIDs:

![JDBCTypeOtherASUUID_4](https://user-images.githubusercontent.com/120391554/207637822-63d1d52b-183b-4635-b984-13b9f4d4e7b7.PNG)

Part of the check involves calling the JDBCTypeWrapper.isAbleASUUID() method. As the JDBCType is OTHER, this method call returns true and causes a UUID object to be instantiated from the string and used as a parameter in the 
prepared statement. This UUID instance then causes the exception when the underlying prepared statement is executed.

The most obvious fix for this would be to remove JdbcType.OTHER as a valid option in the JDBCTypeWrapper.isAbleASUUID() method. Not sure the implications for other databases however...

**Comment by yogeshkul** [comment] 2022-12-15 03:53
Spot on. That's what I found too.
I also read about the castUUID attribute but I don't quite understand how to use it. The documentation around it is not great. 

If an API is exposed to set castUUID to true/false and if this check is used inside JDBCTypeWrapper.isAbleASUUID() then that would work too.

**Comment by tsegismont** [comment] 2022-12-20 17:05
If the default behavior does not work for you, you can change the `JDBCEncoder` implementation by providing a class name in a `META-INF/services/io.vertx.ext.jdbc.spi.JDBCEncoder`.

For example, your custom encoder would extend `JDBCEncoderImpl` and override `io.vertx.ext.jdbc.spi.impl.JDBCEncoderImpl#encodeData`

**Comment by smithp1010** [comment] 2022-12-21 11:09
Thanks for the suggestion. We are looking at adding an "encodeCls' property to activate a custom JDBCEncoderImpl but your suggestion seems like a cleaner way of doing the same. It would still be nicer to get the core functionality changed/fixed so others do not walk into the same issue however :) 

Regarding your question on why column is resolved to OTHER: I have been analysing and it looks like calls on the metadata to getParameterType , getParameterTypeName, etc do throw a SQLException before the underlying statement is executed on the database. This behaviour results in the resolution to OTHER. Only once the statement is executed does the metadata method calls start giving back the correct values:

![JDBCTypeOther_5](https://user-images.githubusercontent.com/120391554/208890391-63f0855f-1eb6-4a6f-a8e3-11b7524c9080.PNG)

Full stacktrace:

java.sql.SQLFeatureNotSupportedException: Unsupported feature: checkValidIndex
	at oracle.jdbc.driver.OracleParameterMetaData.checkValidIndex(OracleParameterMetaData.java:218)
	at oracle.jdbc.driver.OracleParameterMetaData.getParameterType(OracleParameterMetaData.java:329)
	at io.vertx.ext.jdbc.spi.JDBCColumnDescriptorProvider.lambda$null$6(JDBCColumnDescriptorProvider.java:61)
	at io.vertx.jdbcclient.impl.actions.JDBCPropertyAccessor.lambda$create$0(JDBCPropertyAccessor.java:38)
	at io.vertx.jdbcclient.impl.actions.JDBCColumnDescriptor.create(JDBCColumnDescriptor.java:72)
	at io.vertx.ext.jdbc.spi.JDBCColumnDescriptorProvider.lambda$fromParameterMetaData$9(JDBCColumnDescriptorProvider.java:60)
	at io.vertx.ext.jdbc.spi.impl.JDBCEncoderImpl.encode(JDBCEncoderImpl.java:51)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.fillStatement(JDBCPreparedQuery.java:142)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:63)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:44)
	at io.vertx.ext.jdbc.impl.JDBCConnectionImpl.lambda$schedule$3(JDBCConnectionImpl.java:219)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by tsegismont** [comment] 2022-12-21 15:48
> We are looking at adding an "encodeCls' property to activate a custom JDBCEncoderImpl but your suggestion seems like a cleaner way of doing the same.

We already have the service loader mechanism to choose an implementation class, so we would probably not add another one.

> Full stacktrace:
> 
> java.sql.SQLFeatureNotSupportedException: Unsupported feature: checkValidIndex at oracle.jdbc.driver.OracleParameterMetaData.checkValidIndex(OracleParameterMetaData.java:218)

Which version of the ojdbc driver do you use? It should be supported in modern versions.

**Comment by smithp1010** [comment] 2022-12-21 15:58
I'm using Java 17 with this oracle jdbc driver:

  <dependency>
      <groupId>com.oracle.database.jdbc</groupId>
      <artifactId>ojdbc11</artifactId>
      <version>21.7.0.0</version>
  </dependency>

The oracle docs say: "Supports JDBC 4.3 spec and for use with JDK11, JDK12, JDK13, JDK14 and JDK15. ". I'm guessing that this is just out of date and supports JDK17 too. This was the latest version until 21.8.0.0 was released on 6th Dec.

**Comment by smithp1010** [comment] 2022-12-21 16:03
Also, have been running the test case on both Oracle XE (the cutdown free version) and a rather large Oracle RAC Cluster set-up. The problem occurs on both

**Comment by tsegismont** [comment] 2022-12-21 16:20
Thank you @smithp1010 

It seems Oracle does not support param metadata on prepared statements (see https://github.com/oracle/node-oracledb/issues/679).
From my experience with reactive SQL clients, it's probably something only PostgreSQL supports.

@zero88 @pmlopes perhaps our encoder should not rely on an API that's supported by a single DB vendor?

In any case, it would be better not to invoke parameter metadata API on every DB query (due to the performance implications of creating exceptions with stacktraces by the driver).

**Comment by u-ways** [comment] 2023-09-01 13:16
Unfortunately in my case the database I was working had been storing the values using JDK's UUID toString's representation (i.e. `*-*-*-*-*`) as a `VARCHAR(100)`...

I have found a rather ugly workaround:

```kotlin
    /**
     * The only solution so far:
     * - Given our "UUID Byte -- VARCHAR2" test passed, we know that we can insert UUID byte array to VARCHAR2 column.
     * - So we can use RAWTOHEX to convert UUID byte array to VARCHAR2,
     * - Then we can use SUBSTR to split the VARCHAR2 into 5 parts,
     * - Afterwards we can use || to concatenate the 5 parts into a UUID string
     * - and then insert them into a VARCHAR2 column.
     *
     * Thus bypassing the ColumnDescriptor interrogation, but still inserting a UUID as a VARCHAR2 column.
     *
     * REF:
     * - https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/RAWTOHEX.html#GUID-F86E3B5B-7FEE-47FD-A0C2-2FC55DC21C9E
     * - https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/SUBSTR.html#GUID-C8A20B57-C647-4649-A379-8651AA97187E
     */
    @Test
    fun `Solution - Converting the UUID as Byte, convert to RAWTOHEX and then format to UUID toString's BNF`() =
        runBlockingWithTimeoutUnit(ofSeconds(60), EmptyCoroutineContext) {
            val uuid = UUID.randomUUID()

            val connection = SharedDbClient.pool.connection.await()
            val template = """
                                INSERT INTO $TEST_TABLE ($TEST_STRING_COLUMN_KEY) 
                                VALUES (
                                    SUBSTR(RAWTOHEX(#{$STRING_KEY}), 1, 8)  || '-' ||
                                    SUBSTR(RAWTOHEX(#{$STRING_KEY}), 9, 4)  || '-' ||
                                    SUBSTR(RAWTOHEX(#{$STRING_KEY}), 13, 4) || '-' ||
                                    SUBSTR(RAWTOHEX(#{$STRING_KEY}), 17, 4) || '-' ||
                                    SUBSTR(RAWTOHEX(#{$STRING_KEY}), 21)
                                )
                                """

            SqlTemplate
                .forUpdate(connection, template)
                .execute(mapOf(STRING_KEY to uuid.toByteArray()))
                .await()
                .rowCount() shouldBe 1

            val secondConnection = SharedDbClient.pool.connection.await()
            val selectTemplate = "SELECT $TEST_STRING_COLUMN_KEY FROM $TEST_TABLE"

            secondConnection.query(selectTemplate)
                .execute()
                .await()
                .firstOrNull()
                ?.getString(0)
                .shouldNotBeNull()
                .apply { UUID.fromString(this) shouldBe uuid }
        }
```

and a reproducer project can be found here:  https://github.com/u-ways/broken-4.4.5-vertx-jdbc-client-oracle/tree/main

I have also raised https://github.com/vert-x3/vertx-jdbc-client/issues/309 as I noticed this is impacting other types when compared with `4.3.4`.

**Comment by tsegismont** [comment] 2023-11-10 16:45
Closing, if you need special handling of specific columns, use a custom encoder/decoder

**Closed by tsegismont** 2023-11-10 16:45 UTC
Labels: wontfix

**Comment by u-ways** [comment] 2023-11-10 17:04
> Closing, if you need special handling of specific columns, use a custom encoder/decoder

@tsegismont makes sense, thank you. 

Do you have any specific starting points, recommendations or guidance when it comes to implementing a custom encoder/decoder in Vert.x?

**Comment by tsegismont** [comment] 2023-11-14 09:52
@u-ways as a starting point you can extend the default encoder/decoder and override some methods.

Then the documentation explains how to configure the client so that it uses your custom classes.

**Comment by nicolaifriis-nav** [comment] 2024-11-06 13:39
This has become a blocking issue for upgradering to newer versions of Vertx. We are stuck at 4.3.4. We can not predict in an easy way which field might contain a string that gets interpreted as a GUID and triggers the Oracle error Invalid column type.

https://docs.oracle.com/en/error-help/db/ora-17004/?r=23ai

We store all our String values from Java as varchar2 in the database. Most String can potentially contain a GUID and run into this problem. Do we really have to create a workaround / override for every possible String / varchar2 field?

**Comment by tsegismont** [comment] 2024-11-07 15:24
You can override the encoder/decoder to prevent the Vert.x JDBC Client  from transforming strings matching the UUID pattern

See https://vertx.io/docs/vertx-jdbc-client/java/#_data_types

Have you tried this?
