### ISSUE TITLE
prepared query in conjunction with stream doesn't work for Oracle

### ISSUE THREAD

**Issue by ukr15** [vert-x3/vertx-jdbc-client#211] opened 2021-02-22 07:45 UTC
Questions
Do not use this issue tracker to ask questions, instead use one of these channels. Questions will likely be closed without notice.

Version
4.0.2

Context
We tried to migrate our services from Legacy JDBC Client or SqlClient. For Postgres dbms everything works fine as expected, but with Oracle the following exception is signaled:
stream error java.sql.SQLException: Nicht unterstützte Funktion: getMetaData Feb. 18, 2021 7:03:02 VORM. io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
SEVERE: Failed in deploying verticle
java.sql.SQLException: Nicht unterstützte Funktion: getMetaData
at oracle.jdbc.driver.ArrayDataResultSet.getMetaData(ArrayDataResultSet.java:1080)
at io.agroal.pool.wrapper.ResultSetWrapper.getMetaData(ResultSetWrapper.java:460)
at io.vertx.jdbcclient.impl.actions.JDBCQueryAction.decodeReturnedKeys(JDBCQueryAction.java:182)
at io.vertx.jdbcclient.impl.actions.JDBCQueryAction.decode(JDBCQueryAction.java:59)
at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:69)
at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:39)
at io.vertx.ext.jdbc.impl.JDBCConnectionImpl.lambda$schedule$3(JDBCConnectionImpl.java:217)
at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:179)
at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:177)
at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:834)

A similar error was described here: https://groups.google.com/g/vertx/c/H6jGDlkx9No/m/07et_foRDwAJ

Do you have a reproducer?
A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

https://github.com/ukr15/sql-client-error
Steps to reproduce
Unpack archive
Move to src/main/java/de/testVertx4JdbcTest
The program is configured for a postgres database. Configure it for an Oracle Database
mvn clean install
java -jar target/vertx4-jdbc-test-1.0.0-fat.jar → one ore more records should be printed in dependence on the database
Extra
Testet under MacOS and some linux (oracle testing has been done by another party

**Comment by pmlopes** [comment] 2021-06-15 10:22
Duplicate of #222 222

**Closed by pmlopes** 2021-06-15 10:22 UTC
Labels: bug
