### ISSUE TITLE
Vertx executeBatch not returning all rows

### ISSUE THREAD

**Issue by pskarthic** [vert-x3/vertx-jdbc-client#216] opened 2021-03-13 06:31 UTC
I am using vertx JDBC client pool and trying to insert multiple records to table. The insertion is done successfully but the inserted records are not returned instead only first record is returned.

Version - 3.9.4

**Code to insert multiple record using executeBatch**
List<Tuple> batch = new ArrayList<>();
batch.add(Tuple.of(36,"st","st"));
batch.add(Tuple.of(36,"st1","st1"));

pool.preparedQuery("INSERT INTO table (col1,col2,col3) VALUES($1, $2, $3) returning *").executeBatch(batch,rowSetAsyncResult -> {     
            System.out.println("size = " + rowSetAsyncResult.result().size()); // this always return 1
            for(Row row:rowSetAsyncResult.result()){
                System.out.println("id = " + row.getInteger("id"));
            }
        });

**Output:**
size = 1
id = 87

**Extra info:**

DB Postgresql 9.x
OS Mac catalina(same in linux)

**Comment by tsegismont** [comment] 2021-10-20 16:40
I just noticed the parameter placeholder is the dollar sign. So it seems you're using the [Vert.x Pg Client](https://vertx.io/docs/vertx-pg-client/java/), not the [Vert.x JDBC client](https://vertx.io/docs/vertx-jdbc-client/java/).

Can you confirm?

**Comment by tsegismont** [comment] 2021-10-21 12:23
@pskarthic I tried code similar to yours with PgClient:

```java
package io.vertx.pgclient;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.AsyncResult;
import io.vertx.core.Vertx;
import io.vertx.sqlclient.PoolOptions;
import io.vertx.sqlclient.Row;
import io.vertx.sqlclient.RowSet;
import io.vertx.sqlclient.Tuple;

import java.util.ArrayList;
import java.util.List;

public class PgReturning extends AbstractVerticle {

  private PgPool pool;

  public static void main(String[] args) {
    Vertx vertx = Vertx.vertx();
    vertx.deployVerticle(new PgReturning());
  }

  @Override
  public void start() throws Exception {
    pool = PgPool.pool(vertx, new PgConnectOptions()
        .setDatabase("postgres")
        // username
        .setUser("postgres")
        // password
        .setPassword("mysecretpassword"),
      // configure the pool
      new PoolOptions()
        .setMaxSize(16));

    pool.query("DROP TABLE IF EXISTS distributors").execute(this::dropped);
  }

  private void dropped(AsyncResult<RowSet<Row>> ar) {
    if (ar.failed()) {
      ar.cause().printStackTrace();
      return;
    }

    pool.query("CREATE TABLE distributors" +
      "(" +
      "    did  INTEGER," +
      "    name VARCHAR(40)" +
      ")").execute(this::created);
  }

  private void created(AsyncResult<RowSet<Row>> ar) {
    if (ar.failed()) {
      ar.cause().printStackTrace();
      return;
    }

    List<Tuple> batch = new ArrayList<>();
    batch.add(Tuple.of(153, "John"));
    batch.add(Tuple.of(36, "Jack"));

    pool.preparedQuery("INSERT INTO distributors (did,name) VALUES($1, $2) RETURNING did, name")
      .executeBatch(batch, this::inserted);
  }

  private void inserted(AsyncResult<RowSet<Row>> ar) {
    if (ar.failed()) {
      ar.cause().printStackTrace();
      return;
    }

    RowSet<Row> result = ar.result();
    do {
      System.out.println("size = " + result.size());
      for (Row row : result) {
        System.out.println("row = " + row.toJson());
      }
    } while ((result = result.next()) != null);
  }
}
```

Output is:

```
size = 1
row = {"did":153,"name":"John"}
size = 1
row = {"did":36,"name":"Jack"}
```

`size = 1` is expected because each item of the batch returns only one row. You have to inspect every `RowSet` returned by the client using `RowSet#next`.

**Comment by tsegismont** [comment] 2021-10-21 12:23
Closing as this is not the right repo and not a bug.

**Closed by tsegismont** 2021-10-21 12:23 UTC
Labels: invalid
